### ISSUE TITLE
deploying issue

### ISSUE THREAD

**Issue by Kallirroi** [Kallirroi/testingiii-gatsby#2]
![image](https://user-images.githubusercontent.com/10440556/86298008-b7d1f680-bbca-11ea-8cc2-9c97e72419e5.png)

this only occurs when its hooked up to `testingiii` - maybe the User type isn't imported properly or set to null or sth?

**Comment by Kallirroi** [comment]
![image](https://user-images.githubusercontent.com/10440556/86384693-18117880-bc5d-11ea-9d0c-ff02ab4a8d82.png)
but I know how to fix this I think

**Comment by agnescameron** [comment]
oo hm -- I'm gonna try running it locally w/ testingiv and see if i get the same error

**Comment by agnescameron** [comment]
this built fine for me locally (yarn install + gatsby develop)
